spring.application.name=evalur
server.port=${SERVER_PORT:8081}

# 1. Database Connection
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# 2. Hibernate / JPA Configuration

# For development, we can use 'create' to auto-generate the schema. In production, this should be 'validate' or 'none'.
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Industry Standard: use snake_case in DB but camelCase in Java
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy

# Give Neon up to 30 seconds to wake up from zero-compute sleep
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.maximum-pool-size=5

#3 JWT Configuration
evalur.jwt.secret=${JWT_SECRET}
evalur.jwt.expirationMs=${JWT_EXPIRATION_MS} 


#4 Client URL (for CORS configuration)
evalur.client.url=${CLIENT_URL}


#llama doc parser configuration
# File Upload Limits (Important for PDFs)
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# LlamaParse Config
evalur.ai.llamaparse.api-key=${LLAMAPARSE_API_KEY}
evalur.ai.llamaparse.base-url=${LLAMAPARSE_API_BASE_URL}


#GOOGLE GEMINI CONFIG
evalur.ai.google-gemini.api-key=${GOOGLE_GEMINI_API_KEY}